<?php
$phrase['Adresse'] = "Adresse";
$phrase['AEcritLe'] = "a écrit le";
$phrase['AjouterUnArticle'] = "Ajouter un article";
$phrase['AjouterUnArticlePresse'] = "Ajouter un article de presse";
$phrase['AjouterUneNews'] = "Ajouter une brève";
$phrase['AjouterUnPaiement'] = "Ajouter un paiement Paypal";
$phrase['AjouterUnProduit'] = "Ajouter un produit";
$phrase['AjouterUnTheme'] = "Ajouter un thème";
$phrase['ArticleRevue'] = "Photo de l'article";
$phrase['AstuceAnglais'] = "En anglais";
$phrase['AstuceArticleRevue'] = "Indiquez le nom de la photo et téléchargez le fichier.";
$phrase['AstuceAuteurs'] = "";
$phrase['AstuceAuteurEvenement'] = "Information non affichée sur le site";
$phrase['AstuceAutoriserCommentaire'] = "";
$phrase['AstuceClassement'] = "En chiffres";
$phrase['AstuceContenu'] = "";
$phrase['AstuceCouverture'] = "Indiquez le nom de l'image de la couverture et téléchargez le fichier";
$phrase['AstuceDateDuBillet'] = "Ecrire JJ-MM-AAAA";
$phrase['AstuceFrancais'] = "En français";
$phrase['AstuceHeure'] = "Ecrire sous la forme 00:00";
$phrase['AstuceLangue'] = "";
$phrase['AstuceMinuscules'] = "Ecrire en minsucules";
$phrase['AstuceMontant'] = "Ecrire 00,00";
$phrase['AstuceNiveau'] = "";
$phrase['AstuceNomPays'] = "en Français";
$phrase['AstucePageAccueil'] = "Détermine si l'image est reprise en vignette sur la page d'accueil ou non.";
$phrase['AstucePays'] = "Facultatif";
$phrase['AstucePhoto'] = "Nom du fichier image";
$phrase['AstuceRubrique'] = "Sélectionnez une rubrique dans la liste ci-dessus";
$phrase['AstuceTelephone'] = "Ecrire 00.00.00.00.00";
$phrase['AstuceTexte'] = "Mettez en forme votre texte avec les boutons";
$phrase['AstuceTheme'] = "Sélectionnez-en un si nécessaire";
$phrase['AstuceTitle'] = "Trois-quatre mots clés";
$phrase['AstuceTitre'] = "Un titre clair";
$phrase['AstuceTitreMenu'] = "Un titre très court";
$phrase['Auteurs'] = "Auteurs";
$phrase['Classement'] = "Ordre d'apparition";
$phrase['CodePostal'] = "Code postal";
$phrase['ContactEvenement'] = "Pour plus d'infos";
$phrase['ContenuNews'] = "Rubrique";
$phrase['Couverture'] = "Couverture de la revue";
$phrase['DateDebut'] = "Visible à partir du";
$phrase['DateEnvoi'] = "Envoyé le";
$phrase['DateFin'] = "Visible jusqu'au";
$phrase['DatePublication'] = "Date de publication";
$phrase['DesArticlesPresse'] = "des articles de presse";
$phrase['Description'] = "Description";
$phrase['DesMessages'] = "des messages";
$phrase['DesNews'] = "des brèves d'actualité";
$phrase['DesPaiements'] = "des paiements";
$phrase['DesProduits'] = "des produits";
$phrase['DesThemes'] = "des thèmes";
$phrase['Email'] = "Email";
$phrase['EnAnglais'] = "En anglais";
$phrase['EnFrançais'] = "En français";
$phrase['EnLigne'] = "En ligne";
$phrase['Fax'] = "N° de fax";
$phrase['HorsLigne'] = "Hors ligne";
$phrase['ImageTheme'] = "Image du thème";
$phrase['Langue'] = "Langue";
$phrase['MotsCles'] = "Mots clés";
$phrase['NonPageAccueil'] = "Non, uniquement comme thème";
$phrase['NomProduit'] = "Nom du produit";
$phrase['NomRevue'] = "Nom de la revue";
$phrase['OuiPageAccueil'] = "Oui, comme illustration";
$phrase['PageAccueil'] = "En page d'accueil";
$phrase['ParDefaut'] = "Par défaut";
$phrase['PhraseCourte'] = "Une phrase courte";
$phrase['Prix'] = "Prix";
$phrase['PublieLe'] = "Publié le";
$phrase['SiteInternet'] = "Site internet";
$phrase['Telephone'] = "N° de téléphone";
$phrase['UnArticlePresse'] = "un article de presse";
$phrase['UnMessage'] = "un message";
$phrase['UneNews'] = "une brève";
$phrase['UnPaiement'] = "un paiement";
$phrase['UnProduit'] = "un produit";
$phrase['UnTheme'] = "un thème";
$phrase['Ville'] = "Commune";
$phrase['VotreAdresse'] = "Adresse";
$phrase['VotreCP'] = "Code postal";
$phrase['DatePaiement'] = "Date";
$phrase['VotreEmail'] = "Email";
$phrase['VotreMessage'] = "Message";
$phrase['VotreMontant'] = "Montant";
$phrase['VotreNom'] = "Nom";
$phrase['VotreObjet'] = "Objet";
$phrase['VotrePrenom'] = "Prénom";
$phrase['VotreTexte'] = "Votre texte";
$phrase['VotreTheme'] = "Votre thème";
$phrase['VotreTitle'] = "Votre title";
$phrase['VotreTitre'] = "Votre titre";
$phrase['VotreVille'] = "Ville";



// MOTS
$mot['Accueil'] = "Accueil";
$mot['Adresse'] = "Adresse";
$mot['Affichage'] = "Affichage";
$mot['Anglais'] = "Anglais";
$mot['Commentaire'] = "Commentaire";
$mot['Commentaires'] = "Commentaires";
$mot['CP'] = "Code postale";
$mot['Date'] = "Date";
$mot['Defaut'] = "Défaut";
$mot['Email'] = "Email";
$mot['Envoyer'] = "Envoyer";
$mot['Fax'] = "Fax";
$mot['Francais'] = "Français";
$mot['Image'] = "Image";
$mot['Langue'] = "Langue";
$mot['Message'] = "Message";
$mot['Messages'] = "Messages";
$mot['Montant'] = "Montant";
$mot['Nature'] = "Nature";
$mot['News'] = "Brèves";
$mot['Nom'] = "Nom";
$mot['Objet'] = "Objet";
$mot['Paiements'] = "Paiements";
$mot['Photo'] = "Photo";
$mot['Prenom'] = "Prénom";
$mot['Presse'] = "Presse";
$mot['Produits'] = "Produits";
$mot['Rubrique'] = "Rubrique";
$mot['Tel'] = "Téléphone";
$mot['Themes'] = "Thèmes";
$mot['Ville'] = "Ville";


$url['BaseFichierComment'] = "textes/commentaires/";

$tab['LargeurImages'] = array( 	"" => "...",
																"155" => "couverture de magazines",
							 									"610" => "article de presse",
																"600" => "image plein écran",
																"150" => "image largeur 150px", 
																"300" => "image largeur 300px", 
																"450" => "image largeur 450px" );

?>